[pytest]
markers =
    smoke: быстрые критические тесты
    regression: полное покрытие API
    positive: позитивные тесты
    negative: негативные тесты
    pet: тесты Pet API
    user: тесты User API